apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filevault-uploads
  namespace: filevault
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi