FROM rust:bookworm AS builder
WORKDIR /app
ENV SQLX_OFFLINE=true
ENV PROTOC=/usr/bin/protoc
RUN apt-get update && apt-get install -y --no-install-recommends protobuf-compiler && rm -rf /var/lib/apt/lists/*
COPY Cargo.toml Cargo.lock ./
COPY build.rs ./build.rs
COPY proto ./proto
COPY .sqlx ./.sqlx
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release || true
COPY src ./src
COPY benches ./benches
COPY filevault-cli ./filevault-cli
RUN cargo build --release
FROM debian:bookworm-slim
RUN apt-get update && apt-get install netcat-openbsd -y --no-install-recommends \
ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/file_vault ./file_vault
RUN mkdir -p /app/server_files
RUN mkdir -p /app/log_files
EXPOSE 8081
ENTRYPOINT ["./file_vault"]