FROM rust:1.88-slim AS builder
WORKDIR /app
ENV SQLX_OFFLINE=true
COPY Cargo.toml Cargo.lock ./
COPY .sqlx ./.sqlx
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release || true
COPY src ./src
COPY benches ./benches
RUN cargo build --release --bin server
FROM debian:bookworm-slim
RUN apt-get update && apt-get install netcat-openbsd -y --no-install-recommends \
ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/server ./server
RUN mkdir -p /app/server_files
RUN mkdir -p /app/log_files
EXPOSE 8080
ENTRYPOINT ["./server"]