replicaCount: 2

image:
  repository: filevault-server
  tag: "0.1" # Version définie dans les manifests k8s
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8443

ingress:
  enabled: true
  host: filevault.local
  tlsSecretName: filevault-tls

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 1000m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

postgresql:
  enabled: true
  storage: 20Gi

config:
  logLevel: info
  maxUploadSize: '5368709120'