apiVersion: v1
kind: Service
metadata:
  name: filevault-api
  namespace: filevault
spec:
  type: ClusterIP
  selector:
    app: filevault
    component: api
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090