apiVersion: v1
kind: Service
metadata:
  name: filevault-api-nodeport
spec:
  type: NodePort
  selector:
    app: filevault
    component: api
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443